version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli aws-sam-cli

  pre_build:
    commands:
      - python -m unittest discover tests
      - scripts/build_app.sh

  build:
    commands:
      # TODO: use env vars
      - >
        sam package
        --template-file infrastructure/cloudformation-app.yml
        --output-template-file packaged-app.yml
        --s3-bucket bananas-as-a-service

  post_build:
    # If this a feature branch, we want a CloudFormation stack created for it, master is auto.
    commands:
      # TODO: use env vars
      - scripts/deploy_feature_branch.sh

artifacts:
  type: zip
  files:
    - packaged-app.yml
