version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - python -m unittest discover tests
  build:
    commands:
      - mkdir build
      - pip install -r requirements.txt -t build
      - cp -r bananas_as_a_service build
  post_build:
    commands:
      # TODO: input params not hard-code bucket
      - >
        aws cloudformation package
        --template-file infrastructure/cloudformation-app.yml
        --output-template-file packaged-app.yml
        --s3-bucket bananas-as-a-service
        --s3-prefix banana-build
        --force-upload
artifacts:
  files:
    - packaged-app.yml
